:sparkles: Added drc implementation of an angular velocity sensor
libhal-google/libhal-rmd pull request #69
Opened 2023-12-29 23:19 UTC by Coreyboy1820

2023-12-29 23:21 UTC, Coreyboy1820 commented
When my branch from libhal/libhal gets merged in then I will amend that change of versions on this pr.

2023-12-29 23:48 UTC, kammce requested changes
A second review will come soon.

2023-12-29 23:48 UTC, kammce commented on conanfile.py
> +    version = "3.0.2"
```suggestion
    version = "3.1.0"
```

Because you are adding a new feature that is available as a new API, you must bump the minor number up for semantic versioning.

2023-12-29 23:56 UTC, Coreyboy1820 commented on conanfile.py
> +    version = "3.0.2"
Ah, makes sense.

2023-12-30 12:51 UTC, kammce approved these changes

2023-12-30 12:59 UTC, merged